#		    MMMMMMMM""M MMP"""""YMM MM"""""""`MM M""M M""MMMM""M							#
#		    MMMMMMMM  M M' .mmm. `M MM  mmmm,  M M  M M  `MM'  M							 	#
#		    MMMMMMMM  M M  MMMMM  M M'        .M M  M MM.    .MM    .d8888b. .d8888b.			#
#		    MMMMMMMM  M M  MMMMM  M MM  MMMb. "M M  M M  .mm.  M    88'  `88 Y8ooooo.			#
#		    M. `MMM' .M M. `MMM' .M MM  MMMMM  M M  M M  MMMM  M    88.  .88       88			#
#		    MM.     .MM MMb     dMM MM  MMMMM  M M  M M  MMMM  M    `88888P' `88888P'			#
#		   MMMMMMMMMMM MMMMMMMMMMM MMMMMMMMMMMM MMMM MMMMMMMMMM									#
#		____________________________________[ Aurhor ]____________________________________		#
#			Author: Joris Rietveld	<jorisrietveld@gmail.com> github.com/jorisrietveld			#
#	 		_ 	_	_ 	_	_ 	_	_ 	_	_ 	_	_ 	_	_ 	_	_ 	_	_	_	_ 			#
#			Project Homepage:																	#
#		 	Licence: GPLv3 - General Public Licence version 3									#
#																								#
#										 Desctiption										#
#

#____________________________________________________/ Image Creation Options |
# This is the file name of the bootable image to create.
BootableImage=jorix.img
# The size of the blocks on the bootable image.
blockSize=512
# The amount of blocks the image should have.
diskSize=100

#________________________________________________________/ Bootloader Options |

firstStage=first_stage

secondStage=second_stage

#_________________________________________________________/ Assembler Options |
assembler=nasm

#___________________________________________________________/ Compile Options |
